export const SONGS_ACTION_TYPES = {
    FETCH_SONGS_START: 'FETCH_SONGS_START',
    FETCH_SONGS_SUCCESS: 'FETCH_SONGS_SUCCESS',
    FETCH_SONGS_FAILED: 'FETCH_SONGS_FAILED',
    UPDATE_SONG: 'UPDATE_SONG',
    RESET_SONGS: 'RESET_SONGS',
};
